version: "3.7"

services:
    db: 
      image: "mcr.microsoft.com/mssql/server"
      environment:
        SA_PASSWORD: "HELLOthere123"
        ACCEPT_EULA: "Y"
    backend:
      depends_on:
        - db
      build:
        context: "."
        dockerfile: "Fontys S6 Project Backend/Dockerfile"
      ports:
        - "8050:80"