version: "3.7"

services:
    db:
      container_name: db
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: example
      ports:
        - "5432:5432"
    adminer:
      container_name: adminer
      image: adminer
      restart: always
      ports:
        - "8055:8080"
    backend:
      container_name: backend
      depends_on:
        - db
      restart: always
      build:
        context: "./backend/Fontys S6 Project Backend"
      environment:
        ASPNETCORE_ENVIRONMENT: "Development"
        Logging__Console__FormatterName: "simple"
      ports:
        - "8050:80"
    frontend:
      container_name: frontend
      build:
        context: "./frontend"
      ports:
        - "8040:8080"